// Generat de harness/gen-rows.mjs din codul original (genXML) si fields.json. Nu edita.
//
// Doua numerotari coexista in D300: cea AFISATA (rd.19 = total taxa colectata) si cea
// ISTORICA din XML (R17_1), pastrata de ANAF de la versiunile vechi ale formularului.
// Acest fisier e singurul loc unde se face traducerea. Modelul de domeniu lucreaza pe
// caile legacy; interfata afiseaza `row`; xml.ts urmeaza XML_ATTRIBUTES in ordine.

export const XML_NAMESPACE = "mfp:anaf:dgti:d300:declaratie:v12";
/** Exact ca in original: schemaLocation ramas pe v11 langa xmlns v12 (defect #1 din inventar). */
export const XML_SCHEMA_LOCATION = "mfp:anaf:dgti:d300:declaratie:v11 d300.xsd";

export interface XmlAttrSpec { attr: string; path: string; via: 'rawValue' | 'editValue' }
export interface XmlCompositeSpec { attr: 'adresa'; composite: true }
export type XmlEntry = XmlAttrSpec | XmlCompositeSpec;

/** Ordinea exacta a atributelor emise de genXML. Atributele cu valoare null se omit. */
export const XML_ATTRIBUTES: readonly XmlEntry[] = [
  { attr: "depusReprezentant", path: "Antet.d_reprezentant", via: "rawValue" },
  { attr: "luna", path: "Antet.metaDate.luna_r", via: "rawValue" },
  { attr: "an", path: "Antet.metaDate.an_r", via: "rawValue" },
  { attr: "bifa_interne", path: "Antet.opInterne.mtdSimplificata", via: "rawValue" },
  { attr: "temei", path: "Antet.metaDate.d_rez", via: "rawValue" },
  { attr: "cuiSuccesor", path: "Antet.cifS", via: "rawValue" },
  { attr: "prenume_declar", path: "semnatura.prenume", via: "rawValue" },
  { attr: "nume_declar", path: "semnatura.nume", via: "rawValue" },
  { attr: "functie_declar", path: "semnatura.smnFnc", via: "rawValue" },
  { attr: "cui", path: "identifCntr.denumire.cif", via: "rawValue" },
  { attr: "den", path: "identifCntr.denumire.den", via: "rawValue" },
  { attr: 'adresa', composite: true },
  { attr: "telefon", path: "identifCntr.contact.telefon", via: "rawValue" },
  { attr: "fax", path: "identifCntr.contact.fax", via: "rawValue" },
  { attr: "mail", path: "identifCntr.contact.email", via: "rawValue" },
  { attr: "banca", path: "identifCntr.banca.den", via: "rawValue" },
  { attr: "cont", path: "identifCntr.banca.iban", via: "rawValue" },
  { attr: "caen", path: "identifCntr.caen", via: "rawValue" },
  { attr: "caen", path: "identifCntr.caen1", via: "rawValue" },
  { attr: "tip_decont", path: "Antet.metaDate.tipDecont", via: "rawValue" },
  { attr: "pro_rata", path: "identifCntr.proRata", via: "rawValue" },
  { attr: "bifa_cereale", path: "date.bife.caption.bifa_cereale", via: "rawValue" },
  { attr: "bifa_mob", path: "date.bife.caption.bifa_mob", via: "rawValue" },
  { attr: "bifa_disp", path: "date.bife.caption.bifa_disp", via: "rawValue" },
  { attr: "bifa_cons", path: "date.bife.caption.bifa_cons", via: "rawValue" },
  { attr: "solicit_ramb", path: "date.rambursare.bifa_rambursare", via: "rawValue" },
  { attr: "nr_evid", path: "Antet.nr_evid", via: "rawValue" },
  { attr: "totalPlata_A", path: "Antet.metaDate.totalPlata_A", via: "rawValue" },
  { attr: "R1_1", path: "date.comert.r1.c2", via: "rawValue" },
  { attr: "R2_1", path: "date.comert.r2.c2", via: "rawValue" },
  { attr: "R3_1", path: "date.comert.r3.c2", via: "rawValue" },
  { attr: "R3_1_1", path: "date.comert.r3_1.c2", via: "rawValue" },
  { attr: "R4_1", path: "date.comert.r4.c2", via: "rawValue" },
  { attr: "R5_1", path: "date.comert.r5.c2", via: "rawValue" },
  { attr: "R5_2", path: "date.comert.r5.c3", via: "rawValue" },
  { attr: "R5_1_1", path: "date.comert.r5_1.c2", via: "rawValue" },
  { attr: "R5_1_2", path: "date.comert.r5_1.c3", via: "rawValue" },
  { attr: "R6_1", path: "date.comert.r6.c2", via: "rawValue" },
  { attr: "R6_2", path: "date.comert.r6.c3", via: "rawValue" },
  { attr: "R7_1", path: "date.comert.r7.c2", via: "rawValue" },
  { attr: "R7_2", path: "date.comert.r7.c3", via: "rawValue" },
  { attr: "R7_1_1", path: "date.comert.r7_1.c2", via: "rawValue" },
  { attr: "R7_1_2", path: "date.comert.r7_1.c3", via: "rawValue" },
  { attr: "R8_1", path: "date.comert.r8.c2", via: "rawValue" },
  { attr: "R8_2", path: "date.comert.r8.c3", via: "rawValue" },
  { attr: "R9_1", path: "date.livrari.r9.c2", via: "rawValue" },
  { attr: "R9_2", path: "date.livrari.r9.c3", via: "rawValue" },
  { attr: "R10_1", path: "date.livrari.r10.c2", via: "rawValue" },
  { attr: "R10_2", path: "date.livrari.r10.c3", via: "rawValue" },
  { attr: "R11_1", path: "date.livrari.r11.c2", via: "rawValue" },
  { attr: "R11_2", path: "date.livrari.r11.c3", via: "rawValue" },
  { attr: "R12_1", path: "date.livrari.r12.c2", via: "rawValue" },
  { attr: "R12_2", path: "date.livrari.r12.c3", via: "rawValue" },
  { attr: "R12_1_1", path: "date.livrari.r12_1.c2", via: "rawValue" },
  { attr: "R12_1_2", path: "date.livrari.r12_1.c3", via: "rawValue" },
  { attr: "R12_2_1", path: "date.livrari.r12_2.c2", via: "rawValue" },
  { attr: "R12_2_2", path: "date.livrari.r12_2.c3", via: "rawValue" },
  { attr: "R13_1", path: "date.livrari.r13.c2", via: "rawValue" },
  { attr: "R14_1", path: "date.livrari.r14.c2", via: "rawValue" },
  { attr: "R15_1", path: "date.livrari.r15.c2", via: "rawValue" },
  { attr: "R16_1", path: "date.livrari.r16.c2", via: "rawValue" },
  { attr: "R16_2", path: "date.livrari.r16.c3", via: "rawValue" },
  { attr: "R64_1", path: "date.livrari.r17.c2", via: "rawValue" },
  { attr: "R64_2", path: "date.livrari.r17.c3", via: "rawValue" },
  { attr: "R65_1", path: "date.livrari.r18.c2", via: "rawValue" },
  { attr: "R65_2", path: "date.livrari.r18.c3", via: "rawValue" },
  { attr: "R17_1", path: "date.livrari.r19.c2", via: "rawValue" },
  { attr: "R17_2", path: "date.livrari.r19.c3", via: "rawValue" },
  { attr: "R18_1", path: "date.achizitiiRO.r20.c2", via: "rawValue" },
  { attr: "R18_2", path: "date.achizitiiRO.r20.c3", via: "rawValue" },
  { attr: "R18_1_1", path: "date.achizitiiRO.r20_1.c2", via: "rawValue" },
  { attr: "R18_1_2", path: "date.achizitiiRO.r20_1.c3", via: "rawValue" },
  { attr: "R19_1", path: "date.achizitiiRO.r21.c2", via: "rawValue" },
  { attr: "R19_2", path: "date.achizitiiRO.r21.c3", via: "rawValue" },
  { attr: "R20_1", path: "date.achizitiiRO.r22.c2", via: "rawValue" },
  { attr: "R20_2", path: "date.achizitiiRO.r22.c3", via: "rawValue" },
  { attr: "R20_1_1", path: "date.achizitiiRO.r22_1.c2", via: "rawValue" },
  { attr: "R20_1_2", path: "date.achizitiiRO.r22_1.c3", via: "rawValue" },
  { attr: "R21_1", path: "date.achizitiiRO.r23.c2", via: "rawValue" },
  { attr: "R21_2", path: "date.achizitiiRO.r23.c3", via: "rawValue" },
  { attr: "R22_1", path: "date.achizitiiIMP.r24.c2", via: "rawValue" },
  { attr: "R22_2", path: "date.achizitiiIMP.r24.c3", via: "rawValue" },
  { attr: "R23_1", path: "date.achizitiiIMP.r25.c2", via: "rawValue" },
  { attr: "R23_2", path: "date.achizitiiIMP.r25.c3", via: "rawValue" },
  { attr: "R25_1", path: "date.achizitiiIMP.r27.c2", via: "rawValue" },
  { attr: "R25_2", path: "date.achizitiiIMP.r27.c3", via: "rawValue" },
  { attr: "R25_1_1", path: "date.achizitiiIMP.r27_1.c2", via: "rawValue" },
  { attr: "R25_1_2", path: "date.achizitiiIMP.r27_1.c3", via: "rawValue" },
  { attr: "R25_2_1", path: "date.achizitiiIMP.r27_2.c2", via: "rawValue" },
  { attr: "R25_2_2", path: "date.achizitiiIMP.r27_2.c3", via: "rawValue" },
  { attr: "R43_2", path: "date.achizitiiIMP.r28.c3", via: "rawValue" },
  { attr: "R44_2", path: "date.achizitiiIMP.r29.c3", via: "rawValue" },
  { attr: "R26_1", path: "date.achizitiiIMP.r30.c2", via: "rawValue" },
  { attr: "R26_1_1", path: "date.achizitiiIMP.r30_1.c2", via: "rawValue" },
  { attr: "R27_1", path: "date.achizitiiIMP.r31.c2", via: "rawValue" },
  { attr: "R27_2", path: "date.achizitiiIMP.r31.c3", via: "rawValue" },
  { attr: "R28_2", path: "date.achizitiiIMP.r32.c3", via: "rawValue" },
  { attr: "R29_2", path: "date.achizitiiIMP.r33.c3", via: "rawValue" },
  { attr: "R30_1", path: "date.achizitiiIMP.r34.c2", via: "rawValue" },
  { attr: "R30_2", path: "date.achizitiiIMP.r34.c3", via: "rawValue" },
  { attr: "R31_2", path: "date.achizitiiIMP.r35.c3", via: "rawValue" },
  { attr: "R32_2", path: "date.achizitiiIMP.r36.c3", via: "rawValue" },
  { attr: "R33_2", path: "date.regularizari.r37.c3", via: "rawValue" },
  { attr: "R34_2", path: "date.regularizari.r38.c3", via: "rawValue" },
  { attr: "R35_2", path: "date.regularizari.r39.c3", via: "rawValue" },
  { attr: "R36_2", path: "date.regularizari.r40.c3", via: "rawValue" },
  { attr: "R37_2", path: "date.regularizari.r41.c3", via: "rawValue" },
  { attr: "R38_2", path: "date.regularizari.r42.c3", via: "rawValue" },
  { attr: "R39_2", path: "date.regularizari.r43.c3", via: "rawValue" },
  { attr: "R40_2", path: "date.regularizari.r44.c3", via: "rawValue" },
  { attr: "R41_2", path: "date.regularizari.r45.c3", via: "rawValue" },
  { attr: "R42_2", path: "date.regularizari.r46.c3", via: "rawValue" },
  { attr: "nr_facturi", path: "date.r47.c1", via: "rawValue" },
  { attr: "baza", path: "date.r47.c2", via: "rawValue" },
  { attr: "tva", path: "date.r47.c3", via: "rawValue" },
  { attr: "nr_facturi_primite", path: "date.r48.c1", via: "rawValue" },
  { attr: "baza_primite", path: "date.r48.c2", via: "rawValue" },
  { attr: "tva_primite", path: "date.r48.c3", via: "rawValue" },
  { attr: "nr_fact_emise", path: "date.r49.c1", via: "rawValue" },
  { attr: "total_baza", path: "date.r49.c2", via: "rawValue" },
  { attr: "total_tva", path: "date.r49.c3", via: "rawValue" },
  { attr: "valoare_a", path: "date.nedeductibil.r50.c2", via: "rawValue" },
  { attr: "tva_a", path: "date.nedeductibil.r50.c3", via: "rawValue" },
  { attr: "valoare_a1", path: "date.nedeductibil.r50_1.c2", via: "rawValue" },
  { attr: "tva_a1", path: "date.nedeductibil.r50_1.c3", via: "rawValue" },
  { attr: "valoare_b", path: "date.nedeductibil.r60.c2", via: "rawValue" },
  { attr: "tva_b", path: "date.nedeductibil.r60.c3", via: "rawValue" },
  { attr: "valoare_b1", path: "date.nedeductibil.r60_1.c2", via: "rawValue" },
  { attr: "tva_b1", path: "date.nedeductibil.r60_1.c3", via: "rawValue" },
  { attr: "total_precedent", path: "date.alteInfo.r50.c1", via: "rawValue" },
  { attr: "total_curent", path: "date.alteInfo.r50.c2", via: "rawValue" },
];

/** Partile adresei, concatenate in genXML ca "eticheta: valoare, ..." (judetul prin editValue). */
export const ADRESA_PARTS: readonly { path: string; label: string; via: 'rawValue' | 'editValue' }[] = [
  { path: "identifCntr.adresa.str", label: "strada", via: "rawValue" },
  { path: "identifCntr.adresa.nr", label: "nr", via: "rawValue" },
  { path: "identifCntr.adresa.loc", label: "localitate", via: "rawValue" },
  { path: "identifCntr.adresa.judet", label: "judet", via: "editValue" },
  { path: "identifCntr.adresa.sect", label: "sector", via: "rawValue" },
  { path: "identifCntr.adresa.bloc", label: "bloc", via: "rawValue" },
  { path: "identifCntr.adresa.scara", label: "scara", via: "rawValue" },
  { path: "identifCntr.adresa.etaj", label: "etaj", via: "rawValue" },
  { path: "identifCntr.adresa.apt", label: "apartament", via: "rawValue" },
  { path: "identifCntr.adresa.codPst", label: "cod postal", via: "rawValue" },
];

export type Section = 'comert' | 'livrari' | 'achizitiiRO' | 'achizitiiIMP' | 'regularizari' | 'facturi' | 'nedeductibil' | 'alteInfo';
export interface RowSpec {
  path: string;
  attr: string;
  section: Section;
  /** numarul de rand AFISAT (nrCrt din formular); null pentru randurile fara numar */
  row: string | null;
  col: 'c1' | 'c2' | 'c3';
  label: string;
  /** true daca celula e calculata (protected/readOnly in formular) */
  computed: boolean;
}

export const TABLE_ROWS: readonly RowSpec[] = [
  { path: "date.comert.r1.c2", attr: "R1_1", section: "comert", row: "1", col: "c2", label: "Livrări intracomunitare de bunuri, scutite conform art. 294 alin.(2) lit.a) şi d) din Codul fiscal", computed: false },
  { path: "date.comert.r2.c2", attr: "R2_1", section: "comert", row: "2", col: "c2", label: "Regularizări livrări intracomunitare scutite conform art. 294 alin.(2) lit.a) şi d) din Codul fiscal", computed: false },
  { path: "date.comert.r3.c2", attr: "R3_1", section: "comert", row: "3", col: "c2", label: "Livrări de bunuri sau prestări de servicii pentru care locul livrării/locul prestării este în afara României (în UE sau în afara UE), precum şi livrări intracomunitare de bunuri, scutite conform art. 294 alin.(2) lit.b) şi c) din Codul fiscal, din care:", computed: false },
  { path: "date.comert.r3_1.c2", attr: "R3_1_1", section: "comert", row: "3.1", col: "c2", label: "Prestări de servicii intracomunitare care nu beneficiază de scutire in statul membru in care taxa este datorată", computed: false },
  { path: "date.comert.r4.c2", attr: "R4_1", section: "comert", row: "4", col: "c2", label: "Regularizări privind prestările de servicii intracomunitare care nu beneficiază de scutire in statul membru in care taxa este datorată", computed: false },
  { path: "date.comert.r5.c2", attr: "R5_1", section: "comert", row: "5", col: "c2", label: "Achizitii intracomunitare de bunuri pentru care cumpărătorul este obligat la plata TVA (taxare inversă), din care:", computed: false },
  { path: "date.comert.r5.c3", attr: "R5_2", section: "comert", row: "5", col: "c3", label: "Achizitii intracomunitare de bunuri pentru care cumpărătorul este obligat la plata TVA (taxare inversă), din care:", computed: false },
  { path: "date.comert.r5_1.c2", attr: "R5_1_1", section: "comert", row: "5.1", col: "c2", label: "Achiziţii intracomunitare pentru care cumpărătorul este obligat la plata TVA (taxare inversă), iar furnizorul este înregistrat în scopuri de TVA în statul membru din care a avut loc livrarea intracomunitară", computed: false },
  { path: "date.comert.r5_1.c3", attr: "R5_1_2", section: "comert", row: "5.1", col: "c3", label: "Achiziţii intracomunitare pentru care cumpărătorul este obligat la plata TVA (taxare inversă), iar furnizorul este înregistrat în scopuri de TVA în statul membru din care a avut loc livrarea intracomunitară", computed: false },
  { path: "date.comert.r6.c2", attr: "R6_1", section: "comert", row: "6", col: "c2", label: "Regularizări privind achiziţiile intracomunitare de bunuri pentru care cumpărătorul este obligat la plata TVA (taxare inversă)", computed: false },
  { path: "date.comert.r6.c3", attr: "R6_2", section: "comert", row: "6", col: "c3", label: "Regularizări privind achiziţiile intracomunitare de bunuri pentru care cumpărătorul este obligat la plata TVA (taxare inversă)", computed: false },
  { path: "date.comert.r7.c2", attr: "R7_1", section: "comert", row: "7", col: "c2", label: "Achizitii de bunuri, altele decat cele de la rd.5 şi 6 si achizitii de servicii pentru care beneficiarul din Romania este obligat la plata TVA (taxare inversa) din care:", computed: false },
  { path: "date.comert.r7.c3", attr: "R7_2", section: "comert", row: "7", col: "c3", label: "Achizitii de bunuri, altele decat cele de la rd.5 şi 6 si achizitii de servicii pentru care beneficiarul din Romania este obligat la plata TVA (taxare inversa) din care:", computed: false },
  { path: "date.comert.r7_1.c2", attr: "R7_1_1", section: "comert", row: "7.1", col: "c2", label: "Achiziţii de servicii intracomunitare pentru care beneficiarul este obligat la plata TVA (taxare inversa)", computed: false },
  { path: "date.comert.r7_1.c3", attr: "R7_1_2", section: "comert", row: "7.1", col: "c3", label: "Achiziţii de servicii intracomunitare pentru care beneficiarul este obligat la plata TVA (taxare inversa)", computed: false },
  { path: "date.comert.r8.c2", attr: "R8_1", section: "comert", row: "8", col: "c2", label: "Regularizări privind achiziţiile de servicii intracomunitare pentru care beneficiarul este obligat la plata TVA (taxare inversa)", computed: false },
  { path: "date.comert.r8.c3", attr: "R8_2", section: "comert", row: "8", col: "c3", label: "Regularizări privind achiziţiile de servicii intracomunitare pentru care beneficiarul este obligat la plata TVA (taxare inversa)", computed: false },
  { path: "date.livrari.r9.c2", attr: "R9_1", section: "livrari", row: "9", col: "c2", label: "Livrări de bunuri şi prestări de servicii taxabile cu cota 21%", computed: false },
  { path: "date.livrari.r9.c3", attr: "R9_2", section: "livrari", row: "9", col: "c3", label: "Livrări de bunuri şi prestări de servicii taxabile cu cota 21%", computed: false },
  { path: "date.livrari.r10.c2", attr: "R10_1", section: "livrari", row: "10", col: "c2", label: "Livrări de bunuri şi prestări de servicii taxabile cu cota 11%", computed: false },
  { path: "date.livrari.r10.c3", attr: "R10_2", section: "livrari", row: "10", col: "c3", label: "Livrări de bunuri şi prestări de servicii taxabile cu cota 11%", computed: false },
  { path: "date.livrari.r11.c2", attr: "R11_1", section: "livrari", row: "11", col: "c2", label: "Livrări de bunuri şi prestări de servicii taxabile cu cota 9% conform art.III din Legea nr.141/ 2025", computed: false },
  { path: "date.livrari.r11.c3", attr: "R11_2", section: "livrari", row: "11", col: "c3", label: "Livrări de bunuri şi prestări de servicii taxabile cu cota 9% conform art.III din Legea nr.141/ 2025", computed: false },
  { path: "date.livrari.r12.c2", attr: "R12_1", section: "livrari", row: "12", col: "c2", label: "Achiziţii de bunuri şi servicii supuse măsurilor de simplificare pentru care beneficiarul este obligat la plata TVA (taxare inversă) , din care:", computed: true },
  { path: "date.livrari.r12.c3", attr: "R12_2", section: "livrari", row: "12", col: "c3", label: "Achiziţii de bunuri şi servicii supuse măsurilor de simplificare pentru care beneficiarul este obligat la plata TVA (taxare inversă) , din care:", computed: true },
  { path: "date.livrari.r12_1.c2", attr: "R12_1_1", section: "livrari", row: "12.1", col: "c2", label: "Achizitii de bunuri si servicii, taxabile cu cota 21%", computed: false },
  { path: "date.livrari.r12_1.c3", attr: "R12_1_2", section: "livrari", row: "12.1", col: "c3", label: "Achizitii de bunuri si servicii, taxabile cu cota 21%", computed: false },
  { path: "date.livrari.r12_2.c2", attr: "R12_2_1", section: "livrari", row: "12.2", col: "c2", label: "Achizitii de bunuri, taxabile cu cota 11%", computed: false },
  { path: "date.livrari.r12_2.c3", attr: "R12_2_2", section: "livrari", row: "12.2", col: "c3", label: "Achizitii de bunuri, taxabile cu cota 11%", computed: false },
  { path: "date.livrari.r13.c2", attr: "R13_1", section: "livrari", row: "13", col: "c2", label: "Livrări de bunuri şi prestări de servicii supuse măsurilor de simplificare (taxare inversă)", computed: false },
  { path: "date.livrari.r14.c2", attr: "R14_1", section: "livrari", row: "14", col: "c2", label: "Livrări de bunuri şi prestări de servicii scutite cu drept de deducere, altele decat cele de la rd. 1-3", computed: false },
  { path: "date.livrari.r15.c2", attr: "R15_1", section: "livrari", row: "15", col: "c2", label: "Livrări de bunuri şi prestări de servicii scutite fără drept de deducere", computed: false },
  { path: "date.livrari.r16.c2", attr: "R16_1", section: "livrari", row: "16", col: "c2", label: "Regularizări taxă colectată", computed: false },
  { path: "date.livrari.r16.c3", attr: "R16_2", section: "livrari", row: "16", col: "c3", label: "Regularizări taxă colectată", computed: false },
  { path: "date.livrari.r17.c2", attr: "R64_1", section: "livrari", row: "17", col: "c2", label: "", computed: false },
  { path: "date.livrari.r17.c3", attr: "R64_2", section: "livrari", row: "17", col: "c3", label: "", computed: false },
  { path: "date.livrari.r18.c2", attr: "R65_1", section: "livrari", row: "18", col: "c2", label: "", computed: false },
  { path: "date.livrari.r18.c3", attr: "R65_2", section: "livrari", row: "18", col: "c3", label: "", computed: false },
  { path: "date.livrari.r19.c2", attr: "R17_1", section: "livrari", row: "19", col: "c2", label: "TOTAL TAXĂ COLECTATĂ (sumă de la rd.1 până la rd.18, cu excepţia celor de la rd. 3.1, 5.1, 7.1, 12.1, 12.2)", computed: true },
  { path: "date.livrari.r19.c3", attr: "R17_2", section: "livrari", row: "19", col: "c3", label: "TOTAL TAXĂ COLECTATĂ (sumă de la rd.1 până la rd.18, cu excepţia celor de la rd. 3.1, 5.1, 7.1, 12.1, 12.2)", computed: true },
  { path: "date.achizitiiRO.r20.c2", attr: "R18_1", section: "achizitiiRO", row: "20", col: "c2", label: "Achiziţii intracomunitare de bunuri pentru care cumpărătorul este obligat la plata TVA (taxare inversă), din care:", computed: true },
  { path: "date.achizitiiRO.r20.c3", attr: "R18_2", section: "achizitiiRO", row: "20", col: "c3", label: "Achiziţii intracomunitare de bunuri pentru care cumpărătorul este obligat la plata TVA (taxare inversă), din care:", computed: true },
  { path: "date.achizitiiRO.r20_1.c2", attr: "R18_1_1", section: "achizitiiRO", row: "20.1", col: "c2", label: "Achiziţii intracomunitare pentru care cumpărătorul este obligat la plata TVA (taxare inversă), iar furnizorul este înregistrat în scopuri de TVA în statul membru din care a avut loc livrarea", computed: true },
  { path: "date.achizitiiRO.r20_1.c3", attr: "R18_1_2", section: "achizitiiRO", row: "20.1", col: "c3", label: "Achiziţii intracomunitare pentru care cumpărătorul este obligat la plata TVA (taxare inversă), iar furnizorul este înregistrat în scopuri de TVA în statul membru din care a avut loc livrarea", computed: true },
  { path: "date.achizitiiRO.r21.c2", attr: "R19_1", section: "achizitiiRO", row: "21", col: "c2", label: "Regularizări privind achiziţiile intracomunitare de bunuri pentru care cumpărătorul este obligat la plata TVA (taxare inversă)", computed: true },
  { path: "date.achizitiiRO.r21.c3", attr: "R19_2", section: "achizitiiRO", row: "21", col: "c3", label: "Regularizări privind achiziţiile intracomunitare de bunuri pentru care cumpărătorul este obligat la plata TVA (taxare inversă)", computed: true },
  { path: "date.achizitiiRO.r22.c2", attr: "R20_1", section: "achizitiiRO", row: "22", col: "c2", label: "Achizitii de bunuri, altele decat cele de la rd.20 şi 21 si achizitii de servicii pentru care beneficiarul din România este obligat la plata TVA (taxare inversa) din care:", computed: true },
  { path: "date.achizitiiRO.r22.c3", attr: "R20_2", section: "achizitiiRO", row: "22", col: "c3", label: "Achizitii de bunuri, altele decat cele de la rd.20 şi 21 si achizitii de servicii pentru care beneficiarul din România este obligat la plata TVA (taxare inversa) din care:", computed: true },
  { path: "date.achizitiiRO.r22_1.c2", attr: "R20_1_1", section: "achizitiiRO", row: "22.1", col: "c2", label: "Achiziţii de servicii intracomunitare pentru care beneficiarul este obligat la plata TVA (taxare inversă)", computed: true },
  { path: "date.achizitiiRO.r22_1.c3", attr: "R20_1_2", section: "achizitiiRO", row: "22.1", col: "c3", label: "Achiziţii de servicii intracomunitare pentru care beneficiarul este obligat la plata TVA (taxare inversă)", computed: true },
  { path: "date.achizitiiRO.r23.c2", attr: "R21_1", section: "achizitiiRO", row: "23", col: "c2", label: "Regularizări privind achiziţii de servicii intracomunitare pentru care beneficiarul din România este obligat la plata TVA (taxare inversă)", computed: true },
  { path: "date.achizitiiRO.r23.c3", attr: "R21_2", section: "achizitiiRO", row: "23", col: "c3", label: "Regularizări privind achiziţii de servicii intracomunitare pentru care beneficiarul din România este obligat la plata TVA (taxare inversă)", computed: true },
  { path: "date.achizitiiIMP.r24.c2", attr: "R22_1", section: "achizitiiIMP", row: "24", col: "c2", label: "Achiziţii de bunuri şi servicii taxabile cu cota de 21%, altele decât cele de la rd.27", computed: false },
  { path: "date.achizitiiIMP.r24.c3", attr: "R22_2", section: "achizitiiIMP", row: "24", col: "c3", label: "Achiziţii de bunuri şi servicii taxabile cu cota de 21%, altele decât cele de la rd.27", computed: false },
  { path: "date.achizitiiIMP.r25.c2", attr: "R23_1", section: "achizitiiIMP", row: "25", col: "c2", label: "Achiziţii de bunuri şi servicii taxabile cu cota de 11%", computed: false },
  { path: "date.achizitiiIMP.r25.c3", attr: "R23_2", section: "achizitiiIMP", row: "25", col: "c3", label: "Achiziţii de bunuri şi servicii taxabile cu cota de 11%", computed: false },
  { path: "date.achizitiiIMP.r27.c2", attr: "R25_1", section: "achizitiiIMP", row: "26", col: "c2", label: "Achiziţii de bunuri şi servicii supuse măsurilor de simplificare pentru care beneficiarul este obligat la plata TVA (taxare inversă ), din care:", computed: true },
  { path: "date.achizitiiIMP.r27.c3", attr: "R25_2", section: "achizitiiIMP", row: "26", col: "c3", label: "Achiziţii de bunuri şi servicii supuse măsurilor de simplificare pentru care beneficiarul este obligat la plata TVA (taxare inversă ), din care:", computed: true },
  { path: "date.achizitiiIMP.r27_1.c2", attr: "R25_1_1", section: "achizitiiIMP", row: "26.1", col: "c2", label: "Achiziţii de bunuri si servicii, taxabile cu cota 21%", computed: true },
  { path: "date.achizitiiIMP.r27_1.c3", attr: "R25_1_2", section: "achizitiiIMP", row: "26.1", col: "c3", label: "Achiziţii de bunuri si servicii, taxabile cu cota 21%", computed: true },
  { path: "date.achizitiiIMP.r27_2.c2", attr: "R25_2_1", section: "achizitiiIMP", row: "26.2", col: "c2", label: "Achiziţii de bunuri, taxabile cu cota 11%", computed: true },
  { path: "date.achizitiiIMP.r27_2.c3", attr: "R25_2_2", section: "achizitiiIMP", row: "26.2", col: "c3", label: "Achiziţii de bunuri, taxabile cu cota 11%", computed: true },
  { path: "date.achizitiiIMP.r28.c3", attr: "R43_2", section: "achizitiiIMP", row: "27", col: "c3", label: "Compensația în cotă forfetară pentru achiziții de produse și servicii agricole de la furnizori care aplică regimul special pentru agricultori", computed: false },
  { path: "date.achizitiiIMP.r29.c3", attr: "R44_2", section: "achizitiiIMP", row: "28", col: "c3", label: "Regularizări privind compensația în cotă forfetară", computed: false },
  { path: "date.achizitiiIMP.r30.c2", attr: "R26_1", section: "achizitiiIMP", row: "29", col: "c2", label: "Achiziţii de bunuri şi servicii scutite de taxă sau neimpozabile, din care :", computed: false },
  { path: "date.achizitiiIMP.r30_1.c2", attr: "R26_1_1", section: "achizitiiIMP", row: "29.1", col: "c2", label: "Achiziţii de servicii intracomunitare scutite de taxă", computed: false },
  { path: "date.achizitiiIMP.r31.c2", attr: "R27_1", section: "achizitiiIMP", row: "30", col: "c2", label: "TOTAL TAXĂ DEDUCTIBILĂ (sumă de la rd.20 până la rd.28, cu excepţia celor de la rd. 20.1, 22.1, 26.1, 26.2 )", computed: true },
  { path: "date.achizitiiIMP.r31.c3", attr: "R27_2", section: "achizitiiIMP", row: "30", col: "c3", label: "TOTAL TAXĂ DEDUCTIBILĂ (sumă de la rd.20 până la rd.28, cu excepţia celor de la rd. 20.1, 22.1, 26.1, 26.2 )", computed: true },
  { path: "date.achizitiiIMP.r32.c3", attr: "R28_2", section: "achizitiiIMP", row: "31", col: "c3", label: "SUB-TOTAL TAXĂ DEDUSĂ CONFORM ART. 297 ŞI ART. 298 SAU ART. 300 ŞI ART. 298 DIN CODUL FISCAL ȘI COMPENSAȚIE ÎN COTĂ FORFETARĂ", computed: false },
  { path: "date.achizitiiIMP.r33.c3", attr: "R29_2", section: "achizitiiIMP", row: "32", col: "c3", label: "TVA efectiv restituită cumpărătorilor străini, inclusiv comisionul unităţilor autorizate", computed: false },
  { path: "date.achizitiiIMP.r34.c2", attr: "R30_1", section: "achizitiiIMP", row: "33", col: "c2", label: "Regularizări taxă dedusă", computed: false },
  { path: "date.achizitiiIMP.r34.c3", attr: "R30_2", section: "achizitiiIMP", row: "33", col: "c3", label: "Regularizări taxă dedusă", computed: false },
  { path: "date.achizitiiIMP.r35.c3", attr: "R31_2", section: "achizitiiIMP", row: "34", col: "c3", label: "Ajustări conform pro-rata / ajustări de taxă", computed: false },
  { path: "date.achizitiiIMP.r36.c3", attr: "R32_2", section: "achizitiiIMP", row: "35", col: "c3", label: "TOTAL TAXĂ DEDUSĂ (rd.31+rd.32+rd.33+rd.34)", computed: true },
  { path: "date.regularizari.r37.c3", attr: "R33_2", section: "regularizari", row: "36", col: "c3", label: "Suma negativă a TVA în perioada de raportare (rd.35-rd.19)", computed: true },
  { path: "date.regularizari.r38.c3", attr: "R34_2", section: "regularizari", row: "37", col: "c3", label: "Taxa de plată în perioada de raportare (rd.19-rd.36)", computed: true },
  { path: "date.regularizari.r39.c3", attr: "R35_2", section: "regularizari", row: "38", col: "c3", label: "Soldul TVA de plată din decontul perioadei fiscale precedente (rd.45 din decontul perioadei fiscale precedente) neachitate până la data depunerii decontului de TVA", computed: false },
  { path: "date.regularizari.r40.c3", attr: "R36_2", section: "regularizari", row: "39", col: "c3", label: "Diferenţe de TVA de plată stabilite de organele fiscale prin decizie comunicată şi neachitate până la data depunerii decontului de TVA", computed: false },
  { path: "date.regularizari.r41.c3", attr: "R37_2", section: "regularizari", row: "40", col: "c3", label: "TVA de plată cumulat (rd.37+rd.38+rd.39)", computed: true },
  { path: "date.regularizari.r42.c3", attr: "R38_2", section: "regularizari", row: "41", col: "c3", label: "Soldul sumei negative a TVA reportate din perioada precedentă pentru care nu s-a solicitat rambursare (rd.46 din decontul perioadei fiscale precedente)", computed: false },
  { path: "date.regularizari.r43.c3", attr: "R39_2", section: "regularizari", row: "42", col: "c3", label: "Diferenţe negative de TVA stabilite de organele de inspecţie fiscală prin decizie comunicată până la data depunerii decontului de TVA", computed: false },
  { path: "date.regularizari.r44.c3", attr: "R40_2", section: "regularizari", row: "43", col: "c3", label: "Suma negativă a TVA cumulate (rd.36+rd.41+rd.42)", computed: true },
  { path: "date.regularizari.r45.c3", attr: "R41_2", section: "regularizari", row: "44", col: "c3", label: "Sold TVA de plată la sfârşitul perioadei de raportare (rd.40-rd.43)", computed: true },
  { path: "date.regularizari.r46.c3", attr: "R42_2", section: "regularizari", row: "45", col: "c3", label: "Soldul sumei negative de TVA la sfârşitul perioadei de raportare (rd.43-rd.40)", computed: true },
  { path: "date.r47.c1", attr: "nr_facturi", section: "facturi", row: null, col: "c1", label: "Facturi emise", computed: false },
  { path: "date.r47.c2", attr: "baza", section: "facturi", row: null, col: "c2", label: "Facturi emise", computed: false },
  { path: "date.r47.c3", attr: "tva", section: "facturi", row: null, col: "c3", label: "Facturi emise", computed: false },
  { path: "date.r48.c1", attr: "nr_facturi_primite", section: "facturi", row: null, col: "c1", label: "Facturi primite", computed: false },
  { path: "date.r48.c2", attr: "baza_primite", section: "facturi", row: null, col: "c2", label: "Facturi primite", computed: false },
  { path: "date.r48.c3", attr: "tva_primite", section: "facturi", row: null, col: "c3", label: "Facturi primite", computed: false },
  { path: "date.r49.c1", attr: "nr_fact_emise", section: "facturi", row: null, col: "c1", label: "Facturi emise conform art. 11 alin. (6) și (7) din Codul fiscal", computed: false },
  { path: "date.r49.c2", attr: "total_baza", section: "facturi", row: null, col: "c2", label: "Facturi emise conform art. 11 alin. (6) și (7) din Codul fiscal", computed: false },
  { path: "date.r49.c3", attr: "total_tva", section: "facturi", row: null, col: "c3", label: "Facturi emise conform art. 11 alin. (6) și (7) din Codul fiscal", computed: false },
  { path: "date.nedeductibil.r50.c2", attr: "valoare_a", section: "nedeductibil", row: "A", col: "c2", label: "Livrări de bunuri şi prestări de servicii realizate a căror TVA aferentă a rămas neexigibilă, existentă în sold la sfârşitul perioadei de raportare, ca urmare a aplicării sistemului TVA la încasare, din care:", computed: false },
  { path: "date.nedeductibil.r50.c3", attr: "tva_a", section: "nedeductibil", row: "A", col: "c3", label: "Livrări de bunuri şi prestări de servicii realizate a căror TVA aferentă a rămas neexigibilă, existentă în sold la sfârşitul perioadei de raportare, ca urmare a aplicării sistemului TVA la încasare, din care:", computed: false },
  { path: "date.nedeductibil.r50_1.c2", attr: "valoare_a1", section: "nedeductibil", row: "A1", col: "c2", label: "Livrări de bunuri şi prestări de servicii realizate în ultimele 6 luni/2 trimestre calendaristice", computed: false },
  { path: "date.nedeductibil.r50_1.c3", attr: "tva_a1", section: "nedeductibil", row: "A1", col: "c3", label: "Livrări de bunuri şi prestări de servicii realizate în ultimele 6 luni/2 trimestre calendaristice", computed: false },
  { path: "date.nedeductibil.r60.c2", attr: "valoare_b", section: "nedeductibil", row: "B", col: "c2", label: "Achiziţii de bunuri şi servicii realizate pentru care nu s-a exercitat dreptul de deducere a TVA aferentă, existentă în sold la sfârşitul perioadei de raportare, ca urmare a aplicării art. 297 alin. (2) şi (3) din Codul fiscal, din care:", computed: false },
  { path: "date.nedeductibil.r60.c3", attr: "tva_b", section: "nedeductibil", row: "B", col: "c3", label: "Achiziţii de bunuri şi servicii realizate pentru care nu s-a exercitat dreptul de deducere a TVA aferentă, existentă în sold la sfârşitul perioadei de raportare, ca urmare a aplicării art. 297 alin. (2) şi (3) din Codul fiscal, din care:", computed: false },
  { path: "date.nedeductibil.r60_1.c2", attr: "valoare_b1", section: "nedeductibil", row: "B1", col: "c2", label: "Achiziţii de bunuri şi servicii realizate în ultimele 6 luni/2 trimestre calendaristice", computed: false },
  { path: "date.nedeductibil.r60_1.c3", attr: "tva_b1", section: "nedeductibil", row: "B1", col: "c3", label: "Achiziţii de bunuri şi servicii realizate în ultimele 6 luni/2 trimestre calendaristice", computed: false },
  { path: "date.alteInfo.r50.c1", attr: "total_precedent", section: "alteInfo", row: null, col: "c1", label: "Valoarea totală a livrărilor/prestărilor din decontul precedent", computed: false },
  { path: "date.alteInfo.r50.c2", attr: "total_curent", section: "alteInfo", row: null, col: "c2", label: "Valoarea totală a livrărilor/prestărilor din decontul curent", computed: false },
];

export const ROW_BY_PATH: ReadonlyMap<string, RowSpec> = new Map(TABLE_ROWS.map((r) => [r.path, r]));
export const ROW_BY_ATTR: ReadonlyMap<string, RowSpec> = new Map(TABLE_ROWS.map((r) => [r.attr, r]));
